[project]
name = "ttcs"
version = "0.2.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cfn-lint>=1.40.2",
    "hyperscale-ozone>=0.17.2",
]
